#include "./TM.h"
#include "../System/Sys.h"
#include "../Gui/gui.h"



void TextureData::reloadInfo(){
    if (!dptr_->texture) {
        dptr_->format = 0;
        dptr_->access = dptr_->width = dptr_->height = 0;
    } else {
        TM::_QueryTexture(
            dptr_->texture,
            &dptr_->format,
            &dptr_->access,
            &dptr_->width,
            &dptr_->height
        );
    }
}

void TextureData::setTexture(SDL_Texture* newTex){
    // if we already had one, and no other Impl is holding it, free it:
    if (dptr_->texture) {
        bool otherAlive = false;
        for (auto &wk : TM::loadedTextures) {
            if (auto sp = wk.lock()) {
                if (sp.get() != dptr_.get() && sp->texture == dptr_->texture) {
                    otherAlive = true;
                    break;
                }
            }
        }
        if (!otherAlive) {
            if (TM::AUTO_DELETE_TEXTURES)
                TM::_DestroyTexture(dptr_->texture);
            else
                TM::outOfScopeTextures.push_back(dptr_->texture);
        }
    }

    dptr_->texture = newTex;
    // immediately re‑query its properties:
    reloadInfo();
}

TextureData::~TextureData(){
    if (dptr_.unique()) {
        if (dptr_->texture) {
            TM::_DestroyTexture(dptr_->texture);
            dptr_->texture = nullptr;
        }
        TM::removeTexture(dptr_);
    }
}

TextureData::TextureData(): dptr_(std::make_shared<Impl>())
{
    // give it a default autogenerated id if you like:
    id = __FILE__ ":" STR(__LINE__);
    TM::registerTexture(dptr_);
}

void TextureData::printf(bool full) const {
    cout << "TextureData(" << endl;
    cout << "\t" << "Texture: " << dptr_->texture << endl;
    cout << "\t" << "Width: " << dptr_->width << endl;
    cout << "\t" << "Height: " << dptr_->height << endl;
    cout << "\t" << "ID: " << id << endl;
    if(full){
        cout << "\t" << "Format: " << dptr_->format << endl;
        cout << "\t" << "Access: " << dptr_->access << endl;
        cout << "\t" << "OrgWidth: " << orgWidth << endl;
        cout << "\t" << "OrgHeight: " << orgHeight << endl;
    }
    cout << ");" << endl;
}



void TM::registerTexture(std::shared_ptr<TextureData::Impl> const& ptr) {
    loadedTextures.push_back(ptr);
}


void TM::removeTexture(std::shared_ptr<TextureData::Impl> dead) {
    auto &v = loadedTextures;
    v.erase(
      std::remove_if(v.begin(), v.end(),
        [&](auto &wk){
          auto sp = wk.lock();
          // remove if expired OR matches the one we’re removing:
          return !sp || sp == dead;
        }
      ),
      v.end()
    );
}



void TM::setAutoDeleteTextures(bool prop){ AUTO_DELETE_TEXTURES = prop; }






int TM::loadTexture(
    TextureData& td, 
    const string& path, 
    const string& id
){
    // Checking the thread ————————————————————————————————————————————————————————————————————— //

    // If the functions hasn't been run from the main thread,
    // make a job for the main thread, so it executes the loadTexture
    // for us, as soon as possible, untill then the thread is waiting
    if(!Sys::isMainThread()){
        Sys::printf_info("ASYNC, SIDE THREAD, LOADING TEXTURE");

        auto job = std::make_shared<asyncData>();
        job->pendingFunction = LOAD_TEXTURE;
        job->params = { td, path, id };

        {
            std::lock_guard lk(Sys::pendingJobsMutex);
            Sys::pendingJobs.push_back(job);
        }

        Sys::pendingJobsCV.notify_all();   // wake up the main loop

        // now wait until the main thread marks it done:
        std::unique_lock lk(Sys::pendingJobsMutex);
        Sys::pendingJobsCV.wait(lk, [&]{ return job->done; });

        return std::any_cast<int>(job->result);
    }

    // —————————————————— Otherwise, we are on the main thread: do the real work ——————————————— //

    // Just in case there was something in the td object, free it ---------------------------------
    td.setTexture(nullptr);

    // Load the image -----------------------------------------------------------------------------
    SDL_Surface* surface = IMG_Load(path.c_str());
    if(surface == nullptr) return TM_SURFACE_CREATE_ERROR;

    // Check the format of the image --------------------------------------------------------------
    if(surface->format->BitsPerPixel != 32){
        SDL_Surface* converted = SDL_ConvertSurfaceFormat(surface, SDL_PIXELFORMAT_RGBA32, 0);
        SDL_FreeSurface(surface);  // Free the original surface
        surface = converted;

        if(surface == nullptr) return TM_SURFACE_CONVERT_ERROR;
    }

    // Create SDL_Texture* ------------------------------------------------------------------------
    SDL_Texture* tex = _CreateTexture(
        Sys::renderer,
        SDL_PIXELFORMAT_RGBA32,
        SDL_TEXTUREACCESS_TARGET,
        surface->w,
        surface->h
    );
    if(tex == nullptr) {
        SDL_FreeSurface(surface);
        return TM_TEXTURE_CREATE_ERROR;
    }

    // Set Scake Mode for the Texture -------------------------------------------------------------
    int err = _SetTextureScaleMode(tex, SDL_ScaleModeLinear);
    if(err){
        SDL_FreeSurface(surface);
        _DestroyTexture(tex);
        return TM_STSM_FAILED;
    }

    // Fill the texture with the image data -------------------------------------------------------
    err = _UpdateTexture(tex, NULL, surface->pixels, surface->pitch);
    if(err){
        SDL_FreeSurface(surface);
        _DestroyTexture(tex);
        return TM_TEXTURE_UPDATE_ERROR;
    }
    
    // Make texture Updatable/Modifiable ----------------------------------------------------------
    if(_SetTextureBlendMode(tex, SDL_BLENDMODE_BLEND)){
        SDL_FreeSurface(surface);
        _DestroyTexture(tex);
        return TM_TEXTURE_SET_BLENDMODE_ERROR;
    }

    // Set the texture ----------------------------------------------------------------------------
    td.setTexture(tex);

    // GET TEXTURE DIMENSIONS ---------------------------------------------------------------------
    td.reloadInfo();
    td.orgWidth = td.getWidth();
    td.orgHeight = td.getHeight();

    // FILL TD DATA -------------------------------------------------------------------------------
    td.path = path;
    if(id.empty()) td.id = fs::path(path).filename().string();
    else td.id = id;

    // CLEAN UP ---------------------------------------------------------------------------
    SDL_FreeSurface(surface);

    return NO_ERROR;
}


int TM::createTextTexture(
    TextureData& td,
    const string& text,
    int fontSize,
    SDL_Color color
) {
    // Checking the thread ————————————————————————————————————————————————————————————————————— //

    // If the functions hasn't been run from the main thread,
    // make a job for the main thread, so it executes the createTextTexture
    // for us, as soon as possible, untill then the thread is waiting
    if(!Sys::isMainThread()){
        auto job = std::make_shared<asyncData>();
        job->pendingFunction = CREATE_TEXT_TEXTURE;
        job->params = { td, text, fontSize, color };

        {
            std::lock_guard lk(Sys::pendingJobsMutex);
            Sys::pendingJobs.push_back(job);
        }

        Sys::pendingJobsCV.notify_all();   // wake up the main loop

        // now wait until the main thread marks it done:
        std::unique_lock lk(Sys::pendingJobsMutex);
        Sys::pendingJobsCV.wait(lk, [&]{ return job->done; });

        return std::any_cast<int>(job->result);
    }

    // —————————————————— Otherwise, we are on the main thread: do the real work ——————————————— //
    
    if(Sys::fontPath == "") {
        CHECK_ERROR(SYS_FONT_NOT_INITED);
        exit(EXIT_FAILURE);
    }

    // Ensure that privous Texture is de-loaded -----------------------------------------
    td.setTexture(nullptr);

    // Get the font with that particular fontSize
    TTF_Font* font = Sys::getFont(fontSize);

    // Create the text texture and store it as surface ----------------------------------
    SDL_Surface* surface = TTF_RenderUTF8_Blended(font, text.c_str(), color);
    if(surface == nullptr) return TM_SURFACE_CREATE_ERROR;

    // Create texture from it and store it in TextureData
    SDL_Texture* tex = _CreateTextureFromSurface(Sys::renderer, surface);
    if(tex == nullptr) {
        SDL_FreeSurface(surface);
        return TM_TEXTURE_CREATE_ERROR;
    }

    // MAKE TEXTURE UPDATATBLE/MODIFIABLE -------------------------------------------------
    if(_SetTextureBlendMode(tex, SDL_BLENDMODE_BLEND)){
        SDL_FreeSurface(surface);
        _DestroyTexture(tex);
        return TM_TEXTURE_SET_BLENDMODE_ERROR;
    }

    td.path = "TEXT";
    td.id = "TEXT-" + text;

    // SET THE TEXTURE --------------------------------------------------------------------
    td.setTexture(tex);

    // GET TEXTURE DIMENSIONS -------------------------------------------------------------
    td.reloadInfo();
    td.orgWidth = td.getWidth();
    td.orgHeight = td.getHeight();

    SDL_FreeSurface(surface);

    return NO_ERROR;
}


int TM::copyTexture(
    const TextureData& src, 
    TextureData& dst
) {
    // Checking the thread ————————————————————————————————————————————————————————————————————— //

    // If the functions hasn't been run from the main thread,
    // make a job for the main thread, so it executes the copyTexture
    // for us, as soon as possible, untill then the thread is waiting
    if(!Sys::isMainThread()){
        auto job = std::make_shared<asyncData>();
        job->pendingFunction = COPY_TEXTURE;
        job->params = { src, dst };

        {
            std::lock_guard lk(Sys::pendingJobsMutex);
            Sys::pendingJobs.push_back(job);
        }

        Sys::pendingJobsCV.notify_all();   // wake up the main loop

        // now wait until the main thread marks it done:
        std::unique_lock lk(Sys::pendingJobsMutex);
        Sys::pendingJobsCV.wait(lk, [&]{ return job->done; });

        return std::any_cast<int>(job->result);
    }

    // —————————————————— Otherwise, we are on the main thread: do the real work ——————————————— //


    // Check for valid pointers.
    if (!src.getTexture()) {
        return INVALID_ARGUMENTS_PASSED;
    }

    // Create a new texture with the same format, access and dimensions as src.
    SDL_Texture* newTex = _CreateTexture(
        Sys::renderer,
        src.getFormat(),
        src.getAccess(),
        src.getWidth(),
        src.getHeight()
    );
    if(!newTex) return TM_TEXTURE_CREATE_ERROR;

    // Capture the previous target
    auto old_renderTarget = _GetRenderTarget(Sys::renderer);

    // Set the new texture as the render target.
    if (_SetRenderTarget(Sys::renderer, newTex) != 0) {
        _DestroyTexture(newTex);
        return TM_SRT_FAILED; // Set Render Target FAILED.
    }

    // Clear the render target (fill with blue)
    _SetRenderDrawColor(Sys::renderer, 0, 0, 255, 255);
    _RenderClear(Sys::renderer);

    // Copy the source texture onto the new texture.
    if (_RenderCopy(Sys::renderer, src.getTexture(), nullptr, nullptr) != 0) {
        _SetRenderTarget(Sys::renderer, old_renderTarget);
        _DestroyTexture(newTex);
        return TM_RCPY_FAILED; // Render Copy FAILED
    }

    // Reset the render target back to the default
    _SetRenderTarget(Sys::renderer, old_renderTarget);

    // Use the destination object's setTexture method to update its texture.
    dst.setTexture(newTex);

    // Copy metadata from src to dst.
    dst.reloadInfo();
    dst.orgWidth  = src.orgWidth;
    dst.orgHeight = src.orgHeight;
    dst.path      = src.path;
    dst.id        = src.id + "_copy";

    return NO_ERROR; // Success.

}


int TM::resizeTexture(
    TextureData& td,
    int& newWidth,
    int& newHeight
){
    // Checking the thread ————————————————————————————————————————————————————————————————————— //

    // If the functions hasn't been run from the main thread,
    // make a job for the main thread, so it executes the resizeTexture
    // for us, as soon as possible, untill then the thread is waiting
    if(!Sys::isMainThread()){
        auto job = std::make_shared<asyncData>();
        job->pendingFunction = RESIZE_TEXTURE;
        job->params = { td, newWidth, newHeight };

        {
            std::lock_guard lk(Sys::pendingJobsMutex);
            Sys::pendingJobs.push_back(job);
        }

        Sys::pendingJobsCV.notify_all();   // wake up the main loop

        // now wait until the main thread marks it done:
        std::unique_lock lk(Sys::pendingJobsMutex);
        Sys::pendingJobsCV.wait(lk, [&]{ return job->done; });

        return std::any_cast<int>(job->result);
    }

    // —————————————————— Otherwise, we are on the main thread: do the real work ——————————————— //


    if (!td.getTexture()) return INVALID_ARGUMENTS_PASSED;
    if (newWidth == -1 && newHeight == -1) return INVALID_ARGUMENTS_PASSED;

    // Use original dimensions to compute aspect ratio.
    // Assume that td->orgWidth and td->orgHeight hold the original dimensions.
    if (newWidth == -1 && newHeight != -1) {
        newWidth = (newHeight * td.orgWidth) / td.orgHeight;
    } 
    else if (newHeight == -1 && newWidth != -1) {
        newHeight = (newWidth * td.orgHeight) / td.orgWidth;
    }

    // Create a new texture with the same format and access as the source.
    SDL_Texture* newTex = _CreateTexture(
        Sys::renderer,
        td.getFormat(),
        td.getAccess(),
        newWidth,
        newHeight
    );
    if (!newTex) return TM_TEXTURE_CREATE_ERROR;

    // Capture the previous target
    auto old_renderTarget = _GetRenderTarget(Sys::renderer);

    // Set the new texture as the render target.
    if (_SetRenderTarget(Sys::renderer, newTex) != 0) {
        _DestroyTexture(newTex);
        return TM_SRT_FAILED; // Set Render Target FAILED
    }

    // Clear the new texture (fill with blue).
    _SetRenderDrawColor(Sys::renderer, 0, 0, 255, 255);
    _RenderClear(Sys::renderer);

    // Copy from the source texture to the new texture.
    // SDL_RenderCopy will scale the source to fit the destination rectangle.
    SDL_Rect dstRect = { 0, 0, newWidth, newHeight };
    if (_RenderCopy(Sys::renderer, td.getTexture(), nullptr, &dstRect) != 0) {
        _SetRenderTarget(Sys::renderer, old_renderTarget);
        _DestroyTexture(newTex);
        return TM_RCPY_FAILED; // Render Copy FAILED
    }

    // Reset the render target back to the default
    _SetRenderTarget(Sys::renderer, old_renderTarget);

    // Update the TextureData object with the new texture and dimensions.
    td.setTexture(newTex);
    td.reloadInfo();

    return NO_ERROR;
}


int TM::exportTexture(
    const std::string& path, 
    const TextureData& td
) {
    // Checking the thread ————————————————————————————————————————————————————————————————————— //

    // If the functions hasn't been run from the main thread,
    // make a job for the main thread, so it executes the exportTexture
    // for us, as soon as possible, untill then the thread is waiting
    if(!Sys::isMainThread()){
        auto job = std::make_shared<asyncData>();
        job->pendingFunction = EXPORT_TEXTURE;
        job->params = { path, td };

        {
            std::lock_guard lk(Sys::pendingJobsMutex);
            Sys::pendingJobs.push_back(job);
        }

        Sys::pendingJobsCV.notify_all();   // wake up the main loop

        // now wait until the main thread marks it done:
        std::unique_lock lk(Sys::pendingJobsMutex);
        Sys::pendingJobsCV.wait(lk, [&]{ return job->done; });

        return std::any_cast<int>(job->result);
    }

    // —————————————————— Otherwise, we are on the main thread: do the real work ——————————————— //


    if (!td.getTexture() || !Sys::renderer) return -1;

    int width = td.getWidth();
    int height = td.getHeight();

    // Create an SDL_Surface to hold the pixel data.
    SDL_Surface* surface = SDL_CreateRGBSurfaceWithFormat(
        0,                      // Flags
        width,                  // Width
        height,                 // Height
        32,                     // Depth
        SDL_PIXELFORMAT_RGBA32  // Format
    );
    if (!surface) return TM_SURFACE_CREATE_ERROR;

    // Capture the previous target
    auto old_renderTarget = _GetRenderTarget(Sys::renderer);

    // Set the render target to the texture we want to export.
    if (_SetRenderTarget(Sys::renderer, td.getTexture()) != 0) { 
        SDL_FreeSurface(surface); 
        return -3; 
    }

    int err = _RenderReadPixels(
        Sys::renderer, 
        nullptr, 
        surface->format->format, 
        surface->pixels, 
        surface->pitch
    );
    if (err != 0) { 
        _SetRenderTarget(Sys::renderer, old_renderTarget); 
        SDL_FreeSurface(surface); 
        return -4; 
    }

    // Reset the render target back to the default
    _SetRenderTarget(Sys::renderer, old_renderTarget);

    // Attempt to save the surface to a PNG file at the specified path.
    if (IMG_SavePNG(surface, path.c_str()) != 0) { 
        SDL_FreeSurface(surface); 
        return UNKNOWN_ERROR;
    }

    SDL_FreeSurface(surface);
    return NO_ERROR;
}


int TM::exportSurface(
    const std::string& path, 
    SDL_Surface* surface
) {
    // Check if the provided surface pointer is valid.
    if (surface == nullptr) return INVALID_ARGUMENTS_PASSED;

    // Attempt to save the surface to a PNG file at the specified path.
    if (IMG_SavePNG(surface, path.c_str()) != 0) return UNKNOWN_ERROR;

    // Operation succeeded.
    return NO_ERROR;
}



int TM::convert_toTexture(const cv::Mat& cvMat, TextureData& td){
    // Checking the thread ————————————————————————————————————————————————————————————————————— //

    // If the functions hasn't been run from the main thread,
    // make a job for the main thread, so it executes the loadTexture
    // for us, as soon as possible, untill then the thread is waiting
    if(!Sys::isMainThread()){
        auto job = std::make_shared<asyncData>();
        job->pendingFunction = CONVERT_TO_TEX;
        job->params = { cvMat, td };

        {
            std::lock_guard lk(Sys::pendingJobsMutex);
            Sys::pendingJobs.push_back(job);
        }

        Sys::pendingJobsCV.notify_all();   // wake up the main loop

        // now wait until the main thread marks it done:
        std::unique_lock lk(Sys::pendingJobsMutex);
        Sys::pendingJobsCV.wait(lk, [&]{ return job->done; });

        return std::any_cast<int>(job->result);
    }

    // —————————————————— Otherwise, we are on the main thread: do the real work ——————————————— //


    if(cvMat.channels() != 4) return TM_MAT_INVALID_FORMAT;

    SDL_Surface* surface = SDL_CreateRGBSurfaceFrom(
        (void*)cvMat.data,
        cvMat.cols,
        cvMat.rows,
        32,
        static_cast<int>(cvMat.step[0]),
        0x000000ff,
        0x0000ff00,
        0x00ff0000,
        0xff000000
    );
    SDL_Texture* tex = _CreateTextureFromSurface(Sys::renderer, surface);

    // Free the temporary surface.
    SDL_FreeSurface(surface);

    // Retrieve texture dimensions.
    td.reloadInfo();
    td.orgWidth = td.getWidth();
    td.orgHeight = td.getHeight();

    // Store the texture
    td.setTexture(tex);
    return NO_ERROR;
}


int TM::convert_textureTo(const TextureData& td, cv::Mat& cvMat){
    // Checking the thread ————————————————————————————————————————————————————————————————————— //

    // If the functions hasn't been run from the main thread,
    // make a job for the main thread, so it executes the loadTexture
    // for us, as soon as possible, untill then the thread is waiting
    if(!Sys::isMainThread()){
        auto job = std::make_shared<asyncData>();
        job->pendingFunction = CONVERT_TEX_TO;
        job->params = { td, cvMat };

        {
            std::lock_guard lk(Sys::pendingJobsMutex);
            Sys::pendingJobs.push_back(job);
        }

        Sys::pendingJobsCV.notify_all();   // wake up the main loop

        // now wait until the main thread marks it done:
        std::unique_lock lk(Sys::pendingJobsMutex);
        Sys::pendingJobsCV.wait(lk, [&]{ return job->done; });

        return std::any_cast<int>(job->result);
    }

    // —————————————————— Otherwise, we are on the main thread: do the real work ——————————————— //

    // 1) grab the raw SDL_Texture*
    SDL_Texture* tex = td.getTexture();
    if (!tex)
        return TM_GOT_NULLPTR_TEX;

    // 2) pull all the info straight out of the handle
    int w      = td.getWidth();
    int h      = td.getHeight();
    Uint32 fmt = td.getFormat();

    // 3) pick the right OpenCV type
    int bpp = SDL_BYTESPERPIXEL(fmt);
    int cvType = -1;
    switch (bpp)
    {
      case 1: cvType = CV_8UC1; break;
      case 3: cvType = CV_8UC3; break;
      case 4: cvType = CV_8UC4; break;
      default:
        return TM_MAT_INVALID_FORMAT;
    }

    // 4) allocate / resize the Mat
    cvMat.create(h, w, cvType);

    // 5) read back the pixels
    //    save + restore the current render target
    SDL_Texture* oldTarget = _GetRenderTarget(Sys::renderer);
    if (_SetRenderTarget(Sys::renderer, tex))
    {
        _SetRenderTarget(Sys::renderer, oldTarget);
        return TM_SRT_FAILED;
    }

    int pitch = w * bpp;
    int err = _RenderReadPixels(Sys::renderer, nullptr, fmt, cvMat.data, pitch);

    // restore original
    _SetRenderTarget(Sys::renderer, oldTarget);

    if (err)
        return TM_RCLR_FAILED;

    if (fmt == SDL_PIXELFORMAT_RGBA32)
        cv::cvtColor(cvMat, cvMat, cv::COLOR_RGBA2BGR);

    return NO_ERROR;
}




